### ISSUE TITLE
Create new button component

### ISSUE THREAD

**Issue by engenheiracoelho** [Engenheira-Coelho/Curriculo#10]
On this task you should create a new react component, this component should use the json as reference to identify the properties to receive on the component.

```
{
   "pt-br":{
      "download": {
         "title": "Utilizar",
         "icon": " ",
         "link": " "
       },
       "contact": {
          "title": "Contato",
          "icon": " ",
          "link": "  "
       }
}
```

![Image](https://github.com/Engenheira-Coelho/Curriculo/assets/13292181/780e3504-2e84-45c1-8fa0-1a2b8920ab3e)

## Rules:

![Image](https://github.com/Engenheira-Coelho/Curriculo/assets/13292181/d427708e-082c-42c6-8e9e-9257710d56df)

1.  Decorative icon
**Icon**: use [react icon](https://react-icons.github.io/react-icons/). 

2.  Should insert the title based on the property `title` that the component receives as a property.
**Font:** DM Sans
**Color:** #000000
**Size**: 16

**BUTTON COLOR:** #FFFFFF

**Comment by Louis3-silv4** [comment]
Gostaria de pegar essa tarefa,como faço ?
