### ISSUE TITLE
Create new about page

### ISSUE THREAD

**Issue by engenheiracoelho** [Engenheira-Coelho/Curriculo#9]
On this task you should create the about page, at this time we don't have yet a text, use a lorem ipsum just to finish this task and we should define this in the future.

![Image](https://github.com/Engenheira-Coelho/Curriculo/assets/13292181/64166878-a8f8-4bd8-8b58-0b59ca0ce745)

## Rules:

![Image](https://github.com/Engenheira-Coelho/Curriculo/assets/13292181/85d20302-8589-4eb9-b7e0-244b489a4120)

1.  The title
**Font:** Poppins Medium
**Color:** #A6A6A6
**Size:** 71

2.  Simulated text.
**Font:** DM Sans
**Color:** #000000
**Size:** 16

**Comment by camilabdacosta** [comment]
@Andresa43 Ajudou nessa tarefa

**Comment by camilabdacosta** [comment]
O que fizemos:
![image](https://github.com/Engenheira-Coelho/Curriculo/assets/61713785/2d32ee71-7d30-4260-93f2-84fddb53348d)
